#ifndef VORTEX_MSG_H
#define VORTEX_MSG_H

#include <stdint.h>

#define MAGIC_START_BYTE 	0x24
#define MAGIC_STOP_BYTE 	0x40

#define MAX_PAYLOAD_SIZE 16
#define VORTEX_MSG_MAX_SIZE 21
#define VORTEX_MSG_TYPE_INDEX 2
#define VORTEX_MSG_START_DATA_INDEX 3
#define VORTEX_MSG_CRC_BYTE_INDEX 19


typedef enum msg_state
{
	MSG_STATE_MAGIC_BYTES_NOT_RECEIVED,
	MSG_STATE_MAGIC_BYTES_RECEIVED,
	MSG_STATE_SEND_OK,
	MSG_STATE_SEND_FAIL,
	MSG_STATE_RECEIVE_OK,
	MSG_STATE_RECEIVE_FAIL,
}msg_state;

typedef enum msg_type
{
	MSG_TYPE_NOTYPE,
	MSG_TYPE_THRUSTER = 0x41,
	MSG_TYPE_LED = 0x42,
	MSG_TYPE_HEARTBEAT = 0x43,
	MSG_TYPE_ACK = 0x44,
	MSG_TYPE_NOACK = 0x45,
}msg_type;


#endif
